
services:
  serv:
    build: ./src
    ports:
      - 3000:3000
  db:
    image: postgres:15.6
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080