
services:
  serv:
    build: ./src
    ports:
      - 5000:5000
  db:
    image: postgres:15.6
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tictacpostgres
    ports:
      - 5400:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080